#!/bin/bash

# Frontend deployment script for Cloudflare Pages

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

FRONTEND_DIR="frontend"

echo -e "${YELLOW}=== Cloudflare Pages Deployment ===${NC}"
echo ""

# Check if environment variables are set
if [ -z "$CLOUDFLARE_PROJECT_NAME" ]; then
    echo -e "${RED}Error: Cloudflare environment not set!${NC}"
    echo "Please run: source setup-env.sh <environment>"
    exit 1
fi

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
    echo -e "${RED}Error: Supabase environment variables not set!${NC}"
    echo "Please run: source setup-env.sh <environment>"
    exit 1
fi

echo -e "${GREEN}Deploying to Cloudflare Pages project: ${CLOUDFLARE_PROJECT_NAME}${NC}"
echo -e "${GREEN}Environment: ${ENVIRONMENT}${NC}"
echo ""

# Check if wrangler is installed
if ! command -v wrangler &> /dev/null; then
    echo -e "${YELLOW}Wrangler not found. Installing...${NC}"
    npm install -g wrangler
fi

# Generate env.js file with current environment variables
echo -e "${GREEN}Generating env.js...${NC}"
cat > frontend/env.js << EOF
// Environment configuration
// Auto-generated by deploy_frontend.sh - DO NOT EDIT MANUALLY
window.SUPABASE_URL = '${SUPABASE_URL}';
window.SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
window.ENVIRONMENT = '${ENVIRONMENT}';
EOF

echo -e "${GREEN}✓ env.js generated${NC}"
echo ""

# Deploy the frontend
echo -e "${GREEN}Deploying to Cloudflare Pages...${NC}"
wrangler pages deploy "$FRONTEND_DIR" --project-name="$CLOUDFLARE_PROJECT_NAME"

DEPLOY_STATUS=$?
if [ $DEPLOY_STATUS -ne 0 ]; then
    echo -e "${RED}Error: Failed to deploy to Cloudflare Pages.${NC}"
    exit $DEPLOY_STATUS
fi

echo -e ""
echo -e "${GREEN}=== Frontend Deployment Complete ===${NC}"
echo -e "${GREEN}Check the deployment URL above ↑${NC}"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "1. Visit your deployed app using the URL shown above"
echo "2. Test authentication flow"
echo "3. Monitor performance in Cloudflare dashboard"
echo "4. Set up custom domain if needed"