#!/bin/bash

# Frontend deployment script for Cloudflare Pages

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Cloudflare Pages Deployment ===${NC}"

# Check if environment variables are set
if [ -z "$CLOUDFLARE_ACCOUNT_ID" ] || [ -z "$CLOUDFLARE_API_TOKEN" ] || [ -z "$CLOUDFLARE_PROJECT_NAME" ]; then
    echo -e "${RED}Error: Cloudflare environment variables not set!${NC}"
    echo "Please run: source setup-env.sh <environment>"
    exit 1
fi

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
    echo -e "${RED}Error: Supabase environment variables not set!${NC}"
    echo "Please run: source setup-env.sh <environment>"
    exit 1
fi

echo -e "${YELLOW}Deploying to Cloudflare Pages project: $CLOUDFLARE_PROJECT_NAME${NC}"
echo -e "${YELLOW}Environment: $ENVIRONMENT${NC}"

# Check if wrangler is installed
if ! command -v wrangler &> /dev/null; then
    echo -e "${YELLOW}Wrangler not found. Installing...${NC}"
    npm install -g wrangler
fi

# Generate env.js file with current environment variables
echo -e "\n${GREEN}Generating env.js...${NC}"
cat > frontend/env.js << EOF
// Environment configuration
// Auto-generated by deploy_frontend.sh - DO NOT EDIT MANUALLY
window.SUPABASE_URL = '${SUPABASE_URL}';
window.SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
window.ENVIRONMENT = '${ENVIRONMENT}';
EOF

echo -e "${GREEN}✓ env.js generated${NC}"

# Create or update Cloudflare Pages project
echo -e "\n${GREEN}Deploying to Cloudflare Pages...${NC}"

# Check if this is the first deployment
if ! wrangler pages project list | grep -q "$CLOUDFLARE_PROJECT_NAME"; then
    echo -e "${YELLOW}Creating new Cloudflare Pages project...${NC}"
    wrangler pages project create "$CLOUDFLARE_PROJECT_NAME" --production-branch main
fi

# Deploy the frontend
wrangler pages deploy frontend \
    --project-name="$CLOUDFLARE_PROJECT_NAME" \
    --branch="${ENVIRONMENT}"

if [ $? -eq 0 ]; then
    echo -e "\n${GREEN}=== Frontend Deployment Complete ===${NC}"
    echo -e "${YELLOW}Your app is live at:${NC}"
    echo "  https://${CLOUDFLARE_PROJECT_NAME}.pages.dev"
    if [ "$ENVIRONMENT" != "main" ]; then
        echo "  https://${ENVIRONMENT}.${CLOUDFLARE_PROJECT_NAME}.pages.dev"
    fi
else
    echo -e "${RED}✗ Deployment failed${NC}"
    exit 1
fi

echo -e "\n${GREEN}Next steps:${NC}"
echo "1. Visit your deployed app"
echo "2. Test authentication flow"
echo "3. Monitor performance in Cloudflare dashboard"
echo "4. Set up custom domain if needed"